scrape_configs:
  - job_name: "spark-master"
    metrics_path: /metrics/master/prometheus
    static_configs:
      - targets: ["spark-master:8089"]

  - job_name: "spark-worker"
    metrics_path: /metrics/worker/prometheus
    static_configs:
      - targets: ["spark-worker:8088"]

  - job_name: "spark-thrift"
    metrics_path: /metrics/prometheus
    static_configs:
      - targets: ["spark-thrift:4040"]
